name: Code Analysis

on:
  pull_request:
    branches-ignore:
      - backup/*
      
jobs:
  stylecop:

    runs-on:  windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: StyleCop
      run: .github/StyleCopCLI/StyleCopCLI.exe -sln Nojira.sln
